# Generated by Django 2.0.2 on 2018-04-20 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mywatson.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FaceCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.IntegerField(null=True)),
                ('cluster_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('face', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatson.Face')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=mywatson.models.user_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='tag', max_length=100)),
                ('score', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('startX', models.IntegerField(null=True)),
                ('startY', models.IntegerField(null=True)),
                ('endX', models.IntegerField(null=True)),
                ('endY', models.IntegerField(null=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatson.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invertedindex',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywatson.Photo'),
        ),
        migrations.AddField(
            model_name='invertedindex',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywatson.Tag'),
        ),
        migrations.AddField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatson.Photo'),
        ),
        migrations.AddField(
            model_name='face',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatson.Tag'),
        ),
        migrations.AddField(
            model_name='face',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facecluster',
            unique_together={('n_clusters', 'cluster_id', 'face')},
        ),
    ]
