# Generated by Django 2.0.2 on 2018-04-25 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mywatson', '0003_userpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='n_cluster',
            new_name='n_clusters',
        ),
        migrations.AlterUniqueTogether(
            name='userpreferences',
            unique_together={('user', 'n_clusters')},
        ),
    ]
