# Generated by Django 2.0.2 on 2018-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatson', '0004_auto_20180425_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
