# Generated by Django 2.0.2 on 2018-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatson', '0005_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
    ]
