# Generated by Django 2.0.2 on 2018-09-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywatson', '0006_auto_20180918_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField()),
                ('face', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywatson.Face')),
            ],
        ),
    ]
